In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [3]:
df=pd.read_csv('Titanic.csv')

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [7]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [8]:
## train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.3,random_state=42)

In [10]:
x_train.shape

(623, 7)

In [11]:
x_test.shape

(268, 7)

In [12]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [13]:
si=SimpleImputer()
si_em=SimpleImputer(strategy='most_frequent')                        # in this funtion have inside another parameter called strategey which change the value you want on place of null value 
x_train_age=si.fit_transform(x_train[['Age']])
x_test_age=si.fit_transform(x_test[['Age']])
x_train_em=si_em.fit_transform(x_train[['Embarked']])
x_test_em=si_em.fit_transform(x_test[['Embarked']])

In [14]:
x_test_age.shape

(268, 1)

In [15]:
x_train_em.shape

(623, 1)

In [30]:
# 2nd tranformation we have catagorical col also so we used sex,embarked
ohe_sex=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
ohe_emb=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
x_train_sex=ohe_sex.fit_transform(x_train[['Sex']])
x_test_sex=ohe_sex.fit_transform(x_test[['Sex']])
x_train_emb=ohe_emb.fit_transform(x_train_em)
x_test_emb=ohe_emb.fit_transform(x_test_em)

In [31]:
x_train_sex.shape

(623, 2)

In [32]:
x_train_emb.dtype

dtype('float64')

In [33]:
x_train_em.dtype

dtype('O')

In [34]:
# now we combine the all numpy array
x_train_rem=x_train.drop(columns=['Sex','Age','Embarked'])
x_test_rem=x_test.drop(columns=['Sex','Age','Embarked'])

In [35]:
x_train_comb=np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_emb),axis=1)
x_test_comb=np.concatenate((x_test_rem,x_test_age,x_test_sex,x_test_emb),axis=1)

In [36]:
clf=DecisionTreeClassifier()
clf.fit(x_train_comb,y_train)

DecisionTreeClassifier()

In [37]:
y_pred=clf.predict(x_test_comb)

In [38]:
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0])

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7089552238805971

In [50]:
# now if we want to load our model on web and want to through that they input data and on base of this model they prdict they will dead or alive
import pickle

In [52]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_emb,open('models/ohe_emb.pkl','wb'))  # dump the data 
pickle.dump(clf,open('models/clf.pkl','wb'))

In [44]:
# now we input value like web so so imagen it is a web iterface

In [53]:
import pickle
import numpy as np

In [55]:
ohe_sex=pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_emb=pickle.load(open('models/ohe_emb.pkl','rb'))   # we again load the data
clf=pickle.load(open('models/clf.pkl','rb'))

In [ ]:
test_input=np.array([2,'male',32.0,0,5,18.6,'S'],dtype=object).reshape(1,7)

In [56]:
test_input

array([[2, 'male', 32.0, 0, 5, 18.6, 'S']], dtype=object)

In [57]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\HEC\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [58]:
test_input_sex

array([[0., 1.]])

In [60]:
test_input_emb=ohe_emb.transform(test_input[:,-1].reshape(1,1))

In [61]:
test_input_emb

array([[0., 0., 1.]])

In [62]:
test_input_age=test_input[:,2].reshape(1,1)

In [63]:
test_input_age

array([[32.0]], dtype=object)

In [65]:
test_input_comb=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_emb),axis=1)

In [66]:
test_input_comb.shape     #  so see the col is 10 same to same above data

(1, 10)

In [67]:
clf.predict(test_input_comb)

array([1])